version: "3.7"

services:
  r:
    image: internetofwater/r-sta-post:latest
    restart: always
    volumes:
     - type: bind
       source: ./src
       target: /src
     - type: bind
       source: ./src/runner.R
       target: /src/R-Docker-Post-test.R

